services:
  app:
    build:
      context: ./app
      target: ${CONTAINER_ENV:-dev}
    image: gizelle-app-${CONTAINER_ENV:-dev}
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - monreseau
    environment:
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
          # ignore:
          #   - node_modules/
          #   - .nuxt/
        - action: rebuild
          path: ./app/package.json
        - action: rebuild
          path: ./app/pnpm-lock.yaml
        - action: rebuild
          path: ./app/pnpm-workspace.yaml

  db:
    build: ./db
    image: gizelle-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - monreseau

networks:
  monreseau:
